# MP2: Minimum Edit Distance
## Submitted by: Juachon, Jean Philip L. (12083496)

In [113]:
def levDist(word1, word2):
    m = len(word1) #for x axis
    n = len(word2) #for y axis
    table = np.zeros((m + 1, n + 1), dtype = "int64") #initialize an matrix of 0s based on m + 1 * n + 1 (for the null string)

    for i in range(m + 1):
        table[i][0] = i 
    for j in range(n + 1):
        table[0][j] = j 
    for i in range(1, m + 1):
        for j in range(1, n + 1):
            if word1[i - 1] == word2[j - 1]: #if the letters on strings are equal
                table[i][j] = table[i - 1][j - 1] #get the diagonal distance which in this case, is 0 at first
            else:
                table[i][j] = 1 + min(table[i - 1][j], table[i][j - 1], 1+table[i - 1][j - 1])
    return table[-1][-1], table

In [127]:
distance, table = levDist("intention", "execution")
print(f"Minimum edit distance is: {distance}", end = "\n\n")
print("For easier coding, table was set up in a standard way")
print(table, end = "\n\n\n")

print("If basing on the lecture, table is:")
print(np.flipud(table))
print("Either table structure, the results will be the same as the algorithm relies on the left, right, diagonal and string values")

Minimum edit distance is: 8

For easier coding, table was set up in a standard way
[[ 0  1  2  3  4  5  6  7  8  9]
 [ 1  2  3  4  5  6  7  6  7  8]
 [ 2  3  4  5  6  7  8  7  8  7]
 [ 3  4  5  6  7  8  7  8  9  8]
 [ 4  3  4  5  6  7  8  9 10  9]
 [ 5  4  5  6  7  8  9 10 11 10]
 [ 6  5  6  7  8  9  8  9 10 11]
 [ 7  6  7  8  9 10  9  8  9 10]
 [ 8  7  8  9 10 11 10  9  8  9]
 [ 9  8  9 10 11 12 11 10  9  8]]


If basing on the lecture, table is:
[[ 9  8  9 10 11 12 11 10  9  8]
 [ 8  7  8  9 10 11 10  9  8  9]
 [ 7  6  7  8  9 10  9  8  9 10]
 [ 6  5  6  7  8  9  8  9 10 11]
 [ 5  4  5  6  7  8  9 10 11 10]
 [ 4  3  4  5  6  7  8  9 10  9]
 [ 3  4  5  6  7  8  7  8  9  8]
 [ 2  3  4  5  6  7  8  7  8  7]
 [ 1  2  3  4  5  6  7  6  7  8]
 [ 0  1  2  3  4  5  6  7  8  9]]
Either table structure, the results will be the same as the algorithm relies on the left, right, diagonal and string values


In [130]:
def backtrack(D, str1, str2):
    i = len(D) - 1
    j = len(D[0]) - 1
    print(f"String 1: {i}, String 2: {j}")

    operations = []
    while i != 0 or j != 0:
        diagonal = D[i-1,j-1] # Match 
        up = D[i-1,j]       # Delete
        left = D[i,j-1]     # Insert

# if diagonal < left and diagonal < up and str1[i-1] != str2[j-1]:
#   operations.append([str1[i-1], "S", str2[j-1]])
#   i -= 1
#   j -= 1

    # highest priority, insertion
    if up < left and up < diagonal: 
        operations.append([str1[i-1], "D", "-"])
        i -= 1 
    elif left < diagonal: 
        operations.append(["-", "I", str2[j-1]])
        j -= 1
    else:
        if str1[i-1] == str2[j-1]:
            operations.append([str1[i-1], "|", str2[j-1]])
        else:  
            operations.append([str1[i-1], "S", str2[j-1]])

    i -= 1
    j -= 1

    return operations

In [ ]:
a = backtrack(table, "intention", "execution")

In [ ]:
a